---
title: "Final Project Proposal"
subtitle: "Data Science for Biologists, Fall 2021"
author: "Your name goes here"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(warning=FALSE, message=FALSE, echo = TRUE, include = TRUE)
# Load all libraries you use HERE
library(tidyverse)
```



### Introduction

Delete this text and replace with your introduction of the dataset. Make sure you include a properly-formatted link to the data as well.

```{r read-and-glimpse-data}
# Code to read in the data:


# Code to dplyr::glimpse() the data:


```

The variables in the dataset are as follows:

<!-- Delete this HTML comment and instead include a bullet point list or table introducing all variables in the data. -->

<br>

### Proposed model

<!-- Below is a "fill in the blanks!" situation! Delete the blanks, and replace, in order, with 1) either: linear or logistic, 2) the name of the variable **in backticks!!**, like `Species`. ---> 

I plan to use a ______________ model to predict the variable ____________.

