---
title: "Homework 8"
subtitle: "Data Science for Biologists, Spring 2021"
author: "Your name goes here"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
# DO NOT MODIFY THE NEXT LINE:
knitr::opts_chunk$set(warning = FALSE, message = FALSE, echo = TRUE, include = TRUE)

# Load all libraries you use HERE, in this setup chunk:
library(tidyverse)
library(ggforce) # Needed for geom_sina() function
```



## Part 1

### Question 1.1

```{r read_wine_data}
# In this code chunk, read in the CSV files and do some light exploration

```

This text should be REPLACED with your text answer to this question. Again, remember, this is NOT A SCRIPT! This text is not a comment - it is literal markdown text. Outside of code chunks, it's just markdown text. 



### Question 1.2


```{r barplot_version1}
# Create and display the barplot made with wine version 1
# For display, you just have to "run the plotting code" - no need to save to a variable or print! Code chunks behave like "interactive Console code" in the final knitted HTML

```


```{r barplot_version2}
# Create and display the barplot made with wine version 2

```



```{r sina_version1}
# Create and display the sina plot made with wine version 1

```


```{r sina_version2}
# Create and display the sina plot made with wine version 2

```


### Question 1.3



```{r acidity_scatterplot}
# Create and display the scatterplot with the appropriate wine version here
# Reminder: Any exploration code to figure out WHICH wine version should not be here. Just the wrangling and plotting.

```


### Question 1.4



```{r wine_histogram}
# Create and display the faceted histogram with the appropriate wine version here
# Reminder: Any exploration code to figure out WHICH wine version should not be here. Just the wrangling and plotting.

```


## Part 2


```{r read_malaria_data}
# Read in the malaria dataset and display first ten rows by printing it out (or just typing - remember chunks behave like interactive console code!)
```


```{r malaria_lineplot}
# Create your lineplot showing malaria cases over time for three countries of your choosing
```
