---
title: "Lessons from a remote coding class in Fall 2020"
author: "Stephanie J. Spielman"
date: "12/22/2020"
output: 
  html_document:
    theme: readable
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

During Fall 2020, I taught my class [Data Science for Biologists](https://sjspielman.github.io/datascience_for_biologists/) entirely remotely. In this post, I hope to share my miscellenous experiences including what *worked,* what *utterly did not work,* and these lessons will inform my approach to teaching this class remotely again in Spring 2021.

### What is the class?

This class is meant to introduce biology majors (and anyone else who wants to join!) to coding skills using R and tidyverse. The course is geared towards students who have never coded before, but at the same time, the course is not what some might call a "programming class." We don't do any if/else, for loops, writing functions, etc. We focus primarily on working with data for visualization (`ggplot2`), wrangling (`dplyr`, `tidyr`, with a few miscellaneous `forcats` and `stringr` tips), some _light modeling_ (just `lm()` and some `broom` package helpers), as well as other skills for reproducible analyses like Rmarkdown and git(hub) (plus some fundamental UNIX to get them up and running with git). The class meets 3x per week: Two 75 minute lectures and one 2.5 hour lab in order: Lecture/Lab/Lecture. Sometimes lab days had special sets of exercises, but more often we just had a steady stream of class regardless of the "type" of data.

I first launched this class in Spring 2020, when of course we were cut short halfway through the semester and had to transition to remote for the final 6 weeks. So, Fall 2020 was the second time this class was offered, but the first time we *started* remote from the beginning. 

### Everything takes at least 50% more time remotely.

That's it. That's the section. It's _that_ important. Some topics necessarily have to be chucked for remote instruction. Plan accordingly, since you're not going to get to everything you hoped.

### Everyone is exhausted. Build considerations into your class.

This concept must be a guiding principle: We are all emotionally drained beyond capacity. The existential stress of COVID-19 on top of "regular" stress is a force to be reckoned with. I wanted to show my students that mental health considerations were a top priority of mine - you cannot learn if your mental health is suffering. Taking care of yourself emotionally and physically is a key component to the educational process. I took several steps to emphasize this. 

+ I included the following "COVID-19 Statement" in my syllabus. I plan to do this again next spring, and even "after" COVID-19 (note: there is no "after," just a hopefully future where COVID-19 is fully under control). 

```
COVID-19 Statement:

This semester will be one unlike any other, for both students and instructors alike. We will be learning in a new type of environment, with students taking the course from a variety of logistical scenarios. The key goal for this class is to learn new topics, learn how to communicate these new topics, and be engaged with the learning experience. In order to make that happen, we must agree to the following principles.

We will be Kind and Understanding towards one another. 
Unforeseen circumstances will arise that are out of our control. As your instructor, I promise to work with you if/when an unexpected or extenuating circumstance broadly related to the COVID-19 situation affects your ability to participate in class and/or complete assignments in a timely fashion. We are all getting through these difficult times in our own way, so it is important that we cultivate a mutual respect for everyone's personal approaches to these unprecedented societal changes.

We will Take Care of our mental, emotional, and physical health. 
In order to achieve the right mindset for engaged learning, you need to be healthy - all kinds of health!! Maintaining our well-being will be an integrated component of this class. You can expect that we will have regular "check-ins" during class time to talk about how we are managing in this challenging new environment. One key component of protecting your health is to forgive yourself if you are struggling. There will be times when you will struggle this semester, but struggling does not mean you have failed. It means that taking care of yourself is an ongoing process rather than a quick fix. Health does not increase linearly over time - it has ups and downs. Please be forgiving to yourself during any "downs" - I am here for you.

We will be Flexible about some of the course goals and objectives. 
The overall goal for this course is to provide you with a set of practical skills in data analysis, suitable for any field you pursue including biology. While I promise we will achieve these goals, there are likely to be some aspects of the class that we will not get to given the uncertain logistics of the semester. To accommodate this uncertainty, course schedules and materials will be announced, at the very least, on a week-by-week basis. This means we will not have to "rush" through certain materials for the mere sake of advancing to the next section of the course. Instead, the pace of the course will "reveal itself" we learn how to navigate this new learning environment as a team. This also means that the grading scheme is subject to change, in a way that favors YOU. For example, if assignment(s) is/are canceled, this may cause other assignments to count "too much" towards your overall grade. I will make sure your grade is not negatively affected by such circumstances. 
```

+ I allowed students to have up to TWO "Personal Days." A personal day is one where the student has an unexcused absence without needing to provide any reason at all. There are infinite life circumstances when this comes in handy, especially during a semester when I think we all have days where we just **NEED** a break. Students are humans too - let's treat them like it.

+ This semester had another special consideration: The presidential election on Tuesday 11/3. This date was roughly 2/3 through the semester, when everyone was also completely burnt out from the semester itself. I decided to convert this entire week to "Office Hours," and I did not make any assignments due that week. Students had a chance to collect themselves and regroup to be ready for the rest of my class' semester. We did have to sacrifice a topic to make this happen - namely, regular expressions got canned :( - but I figure that students who *really* want to pursue coding in the future will have plenty of future opportunities to learn regex. Since our spring break will be canceled next semester, I intend to have at least 1-2 class days, if not a whole week, mid-semester dedicated to "saving ourselves from burnout." Some institutions are building these days into the spring 2021 schedule, but as mine is not, I will bring my own spring break to the table. 

### Cloud computing

This class was made possible entirely because of the lovely, lovely, LOVELY resource [RStudio Cloud](https://rstudio.cloud/) (shout-out to my superhero sales contact Pete Knast who helped me make it happen at my institution!). Not only does this cloud platform mitigate the hellscape of software installs (I can't begin to fathom doing that remotely) across myriad personal computers, it significantly reduces inequity issues in the classroom. Many of the students at my institution come from underprivileged/underrepresented backgrounds and do not have personal machines that can support the R, RStudio, and tidyverse package downloads. Having access to dedicate cloud resources where I can also disseminate and see student work made a huge difference to running the class as smoothly as possible. Since I have full access to all of students' Cloud projects in our class' workspace, I can easily go into student code and leave helpful comments for questions where they are struggling. 

If you are teaching R, I seriously recommend seeing if you can get onto RStudio Cloud, and/or seeing if your institution would be able to support RStudio Server Pro (free license if used for education!) to set your own analogous situation up. 

### Attendance 

When designing the class, I decided to make 20% of the class grade based on attendance. My initial thought was: Fall 2020 is a wreck, so let's make it easy to get points! Show up and get credit! Midway through the semester, I canceled this grading component and made attendance entirely optional. (Notably, from the beginning, all classes were  recorded - except the one time I forgot to hit the record button.... -  and made available, so students could always go back and catch up on their own time.) I made this attendance policy change for a couple reasons:

+ Many students were simply too overwhelmed with life to be able to fully focus on live class. Some of them had prohibitive work schedules with employers who took advantage of their remote class modalities. Some of them were working from home with families running around in the background causing all kinds of distractions. Indeed, many of our students are URM first-generation to attend college (and note - I am *so proud* to be able to work with this population!!), so their home experiences were fundamentally different from what my own might have been. If I were enrolled in remote classes and Zooming from my bedroom, my parents would have cleared out of the space to give me as much quiet and focus as I needed. Both of my parents have advanced degrees, and all of my grandparents attended college, so this attitude is simply part of the culture in which I (and they!) were raised. This attitude and educational context is foreign to many of my students and their families. I say this NOT AT ALL to denigrate students - I am overjoyed that I can play a role in their educational pursuits!! I say this because my personal background is utterly different from many of my students', and learning to be conscious and understanding of their circumstances is key for my growth as an educator. 

+ I rely on class participation when teaching. This semester's class was pretty small, with 16 students total. About half of them regularly engaged and participated during class, but I often had no clear evidence that the other 8 were paying attention at all (again, not necessarily anyone's "fault" - just a product of Fall 2020 madness). Even for the ones who engaged, verbal engagement was rare (see "Confidence") in next section, and most contributions were a) emoji reaction thumbs-up so I could check that they were with me, and b) Zoom chats which, to my utter disappointment, do not beep! I missed chats from students all the time since Zoom has no audible notification for chats sent during meetings. Even so, not knowing where half my class was at a given time was _rough_. Lecturing into the ZOOM VOID was making me absolutely loopy, and I couldn't take it anymore^[That said, I am endlessly thankful for the 4-5 students who regularly turned on their cameras.]. I figured making attendance optional will both improve the learning environment from the students who were able and wanted to be engaged, while also allowing more flexibility for students who had situations prohibiting them from live participation.

### Material presentation

Usually when I teach coding, I provide students with cheatsheet resources and teach via live-coding. I firmly believe that live-coding is an effective way to *force* students to engage with the code in a supported environment. At my institution, our classrooms are the same as lab rooms. Each table is a workbench that seats 4 students, with 6 tables per classroom, creating a wonderful class size of 24 students. So, during live-coding sessions, students get to *heavily* interact with one another and help each other to debug. When I taught this class in Spring 2020, students at each table group formed robust communities - indeed, I recently heard from a former Spring 2020 student that their table's group chat remains alive and well to this day! In addition, because class sizes are so small, it is straightforward for me to demo a few lines of code, and then float around the classroom to help students catch up as needed. Technical issues were solved on the spot.

None of the above works in a remote setting. None of it. There are a lot of reasons, but in my personal opinion, these are the leading reasons (other than the obvious "we are not in person" aspect):

+ **Internet connectivity.** While some students were lucky to have reliable and strong internet connections, many of them simply did not have a stable enough internet connection to be able to follow live code. This is especially true for  students working from crowded homes where the whole family was WFH, or for students living in dorms competing with all dorm inhabitants for Zoom bandwidth. If your connection drops off for 5 minutes, it's too challenging to catch up to the live coding being presented. Plus, even for the students with the strongest internet connection, there are always little lags that crop up now and again.

+ **Screen real estate.** Watching someone live-code *while* coding along with them requires a hefty monitor. In a classroom where the live code is presented on the overhead projector, this issue doesn't exist. A 13" laptop screen - or "worse," Surface tablet screen - simply will not cut it. You have to simultaneously see, at a font size large enough for your eyeballs, code that you are typing along with, also at a font size large enough for your eyeballs. Therefore, before the semester started, I emailed all students that I strongly recommended buying a (cheap!) external monitor to use to mitigate this issue, or hook up to their TV! However, some students were unable to pursue this approach due to financial considerations. Moreover, some of the students who WERE able to purchase a monitor still felt overwhelmed. As a programmer, I am used to having a lot going on on one large screen. Students are wholly unprepared for that type of screen-information overload, even if there is sufficient space on the monitor.

+ **Choppy presentation.** In person, I can gauge student retention and understanding with facial expressions. If I see small conversations happening at a student table, I can quickly tell that they need help and float over to assist. I can't do any of these things in a remote classroom. All I can really do is pause and wait for feedback from students. The amount of 

+ **Confidence.** It is hard to speak up and ask questions, especially when you have never actually met the professor in person *AND* when you are braving the entirely new and overwhelming landscape of coding. I would regularly prompt students every 3-4 minutes for feedback (I heavily used Zoom's reaction emojis!) about whether they were with me, and I consistently found that half the class was ALWAYS with me, but the other half of the class was too lost to even be able to answer whether they were with me or not. To some degree, this is not preventable, but to some degree, I can improve my presentation to get maybe 75% of them with me at all times.


+ **Hey, it's just Fall 2020.** I was _overwhelmed_ with both a backlog work and a backlog of existential stress this semester. I do not think I would have been able to truly focus on and absorb the material in my classes this semester if I were a college student. I think any student who hanged in all semester long deserves their degree right there on the spot. Watching, and feeling for myself, how everyone's motivation and focus just ramped down..and down...and down.. all semester was a major challenge.

**Therefore, next semester, I'm going to change things up!!!** I plan to use an approach I have just now titled "Show that, show how, and go!". In order, I will..

+ Present slides (made with the crazy useful [xaringan](https://github.com/yihui/xaringan) package) with code. I will explain how the code works at a high level. With this package, I can show code and its output just as I would do for an Rmarkdown knitted HTML. 
+ Demonstrate the same code from the slides *live* - see what's in the slides in action!
+ Have students to run the code themselves for direct engagement

I think this process will take about the same amount of time as me demo'ing code and then waiting 1-4 minutes for students to report back via Zoom emoji that they have completed and are on top of the tasks, so I'm not planning to change materials up too much.

### Remote exercises

For novice students, learning to code is a double hit: They both have to learn the specific functions etc., while also becoming comfortable with working in an IDE. The RStudio IDE is an absolute joy, IMHO, for more experienced programmers, but the interface is bonkers overwhelming for newcomers. For example, closing the editor panel leads to significant panic that the script is gone. In any other circumstance, a student would clearly know that, for example, closing a Word document does not mean that document is now in the trash. But, the overwhelming nature and "newness" of IDE's and coding tend to make students forget things they already know. Furthermore, since we were not in person, I could not quickly float to their table to explain


I attempted breakout rooms, and they simply did not fly. Some students literally signed out of Zoom during breakout room sessions (???), and the students who *needed* the group work seemed to feel abandoned in the breakout room alone (even if I regularly e-floated in, they just sat there and waited for me to come back...not ideal.). The students who were following class closely mostly preferred to work independently. Therefore, after only 2 breakout room attempts, I decided this approach would not serve the students in the class. One reason it might not have worked well is that I didn't *start* the semester with breakout rooms, but only tried to introduce them when we got to two-table `dplyr` verbs, Next semester, I am anticipating a much larger class (33% increase), so perhaps that student population will be more interested in the breakout room concept, _especially_ since they had Fall 2020 to get their feet wet with remote learning.

**Here's what I actually did:** I designed several [`learnr`](https://rstudio.github.io/learnr/) modules for students on a) understanding types of data (numeric, categorical, etc.), b) base R introductory material (using logical operators, defining arrays, using basic functions like `mean()` etc.), c) `ggplot2`, d) and `dplyr` one-table verbs. The modules contained both hints and answers, so students didn't feel lost. Using these modules also removes the overwhelming nature of the RStudio IDE - students can specifically focus on running code without a million buttons and scary places to accidentally click. One student told me that working on these exercises helped her tremendously because "it felt like I [Dr. Spielman] was actually there to explain the concepts." Huge win!!! Since the modules are served on a paid shinyapps tier, I won't share the links here (we need to keep the usage dedicated to the students), but I will be more than happy to share these materials via personal communication!

During class labs, I used a flipped classroom structure to provide students with the time and space to work through these exercises. I answered their questions via chat as they went, and they were able to go at their own pace to manage WFH-based distractions. Next semester, I plan to continue developing these modules for many more topics we cover in class, including more `ggplot2` exercises, two-table `dplyr` verbs, `stringr`, and `tidyr` pivoting. I also want to develop more exercises directly related to debugging code. 