---
title: "Data Science for Biologists, Fall 2021"
output: html_document
---

# THIS COURSE IS NOW READ-ONLY

Dr. Spielman is no longer affiliated with Rowan University.

You can reach [Dr. Spielman](https://sjspielman.github.io) at `stephanie.spielman@gmail.com`.


Content below is preserved from Fall 2021, although links to Shiny Apps are mostly dead.
Most Shiny Apps live in the [`ds4b.materials`](https://github.com/sjspielman/ds4b.materials) (which is also not well maintained).

--------------------------------------------------------------


This website contains all materials used in BIOL 01301 Fall 2021 at Rowan University with Dr. Spielman. (Are you a former student looking for your semester's version of this website? Email Dr. Spielman!)


## Key Information and Links

+ This course meets Monday and Thursday 2-3:15 pm and Wednesday 3:30 - 6:15 pm in Science Hall 126.
+ Virtual Office Hours are 1-3 PM every Tuesday over Zoom (link is in Canvas).
+ All grading and assignment submissions (unless otherwise stated) will be hosted on Canvas.
+ All course materials will be posted on _this site_ and/or within the RStudio Cloud BIOL01301 workspace.
+ The [syllabus](syllabus/docs/index.html) contains all class information and policies.

## Class Schedule and Materials

> Scheduled topics are subject to change up until the week before, depending on class pace. Homeworks will be made available no later than one week in advance of their deadlines.
>
> [Link to the `{introverse}`](https://sjspielman.github.io/introverse)
>
> [All of the colors!!!](./misc/Rcolor.pdf)
>
> [Links to short help videos](./video_links.html)
>
> [`#tidytuesday` instructions](./misc/tidytuesday_instructions.pdf)


 Date  | Topic                                  | In-class materials and other resources        | Assignment DUE to Canvas by 2 PM
:----------|:---------------------------------------|:----------------------------------------------------------|:---------------------------------------------------------------------
W 9/1   | Introduction and class logistics | - | -
R 9/2   | Types of data and figures | ["Types of data and figures" interactive exercises](https://sjspielman.shinyapps.io/data_figures) | -
M 9/6 | _No class: Labor Day_ |- |-
W 9/8   | Types of data and figures  | ["Types of data and figures" interactive exercises](https://sjspielman.shinyapps.io/data_figures) | -
R 9/9   | Concepts in tidy data  | [Tidy data paper](./misc/tidy-data.pdf) | -
M 9/13  | Introduction to R and RStudio | ["Introduction to R" exercises](./exercises/intro_R.html) <br> [Introduction to R stand-alone tutorial](./tutorials/introduction_to_R.html)| -
W 9/15 | Introduction to R and RStudio | ["Introduction to R" exercises](./exercises/intro_R.html) | Homework 1: Identifying data types and figures <br> [Link to Instructions](./homeworks/hw1/hw1_instructions.html) <br> [Link to Answer Sheet](./homeworks/hw1/homework1_answer_sheet.docx)
R 9/16 | Exercise Recap and Introduction to RMarkdown | Rmarkdown activity | -
M 9/20 | The grammar of graphics, Part 1 | [Slides](./slides/grammar_graphics_slides.pdf) | -
W 9/22 | The grammar of graphics, Part 2 <br> Homework 1 Review | Same slides as Monday 9/20  | **HW2 DEADLINE POSTPONED TO FRIDAY 9/24/21 - SEE CANVAS ANNOUNCEMENT** <br> Homework 2: Using R and RMarkdown <br> [Link to Instructions](./homeworks/hw2/hw2_instructions.html) <br> [Starting and submitting HW2 video](https://youtu.be/n7dyNVH0gE0) <br> [Additonal (important!) help videos](./video_links.html) <br><br> [_**ALSO:** watch/follow this video to setup RStudio Cloud/Github_](./tutorials/github_token.html) and complete Canvas assignment: _"Proof of RStudio Cloud/Github Setup"_
R 9/23 | _Open work day_  | | -
M 9/27 | Introduction to `ggplot2` | [Reference slides](./slides/ggplot2_slides.html) <br> [In-class script: Intro to `ggplot2`](./inclass/ggplot2_day1.R) (Upload this to your RStudio Cloud project to open it) | -
W 9/29 | More `ggplot2`  | [Sets 1-5 of "Introduction to `ggplot2`" exercises](./exercises/ggplot2.html) <br> ["Line-by-line" application](https://sjspielman.shinyapps.io/line_by_line) <br> [In-class script: More `ggplot2`](./inclass/ggplot2_day2.R) (Upload this to your RStudio Cloud project to open it) | Homework 3: Grammar of Graphics <br> [Link to Instructions](./homeworks/hw3/hw3_instructions.html) <br> [Link to Answer Sheet](./homeworks/hw3/homework3_answer_sheet.docx)
R 9/30 |  _Open work day_ | | -
M 10/4 | Best practices in data visualization | [Slides](./slides/dataviz_style_slides.pdf) | Nothing due today, but watch Part 6 "Calling Bullshit" for Wednesday
W 10/6 |  Critiquing data viz <br> Customizing your plots in `ggplot2` | [In-class script: Facets and palettes](./inclass/ggplot2_facets_palettes.R)  | Watch Part 6 video playlist (~1 hour) from "Calling Bullshit": <br> [Link from "Calling Bullshit" class website](https://www.callingbullshit.org/videos.html) <br> [Direct YouTube link](https://www.youtube.com/watch?v=T-5aLbNeGo0) <br><br> Homework 4: Data visualization with `ggplot2`<br> [Link to Instructions](./homeworks/hw4/hw4_instructions.html)
R 10/7 |  Introduction to exploratory data analysis | In-class activity | [Background reading: "A hypothesis is a liability"](https://genomebiology.biomedcentral.com/articles/10.1186/s13059-020-02133-w)
M 10/11 | Reading and writing data  | [Reference: reading and writing data and saving figures](./tutorials/readr_ggsave.html) <br> [Download in-class activity](https://github.com/sjspielman/datascience_for_biologists/raw/master/docs/inclass/mammals_activity.zip) |  [Background reading: "FILE NOT FOUND"](https://www.theverge.com/22684730/students-file-folder-directory-structure-education-gen-z)
W 10/13 | Reading and writing data <br>  Introduction to data wrangling with `dplyr` and `tidyr`| See Canvas for spreadsheet links <br> In-class activity from Monday continued | Homework 5: Exploratory data analysis with `ggplot2` <br> [Link to instructions](./homeworks/hw5/hw5_instructions.html)
R 10/14 | Data wrangling with `dplyr` and `tidyr` II | [In-class `dplyr` script from W 10/13- R 10/14](./inclass/notes_intro_dplyr.R) | -
M 10/18 | Data wrangling with `dplyr` and `tidyr` III | [Introduction to `dplyr` exercises Set 1](./exercises/dplyr.html) | -
W 10/20 | Introducing `#tidytuesday` extra credit <br> Data wrangling with `dplyr` and `tidyr` IV | [Introduction to `dplyr` exercises Sets 1-3](./exercises/dplyr.html) | Homework 6: Introduction to data wrangling and visualization <br> [Link to instructions](./homeworks/hw6/hw6_instructions.html)
R 10/21 | Data wrangling with `dplyr` and `tidyr` V |  [Introduction to `dplyr` exercises Sets 2-3](./exercises/dplyr.html)  | -
M 10/25 | Data wrangling with `dplyr` and `tidyr` VI | [Introduction to `dplyr` exercises Sets 2-3](./exercises/dplyr.html)  | - | -
W 10/27 | Exploratory analysis II | [Peer review plots](./misc/exploratory_redux_f21.html) | -
R 10/28 | _Open work day_  | Resource: [Modifying figure sizes](./misc/figure_size_rmd.Rmd) | Homework 7: More data wrangling and visualization due **FRIDAY 10/29 at 11:59 PM** <br> [Link to instructions](./homeworks/hw7/hw7_instructions.html)
M 11/1 | Data reshaping ("pivoting") with `tidyr` I | [HW1 tidy data redux](./homeworks/hw1/hw1_instructions.html) | -
W 11/3 | Data reshaping ("pivoting") with `tidyr` II  | In-class activity: [Let's do HW9!](./homeworks/hw9/hw9_instructions.html)  | Homework 8: Exploratory analysis of coffee ratings <br> [Link to instructions](./homeworks/hw8/hw8_instructions.html)
R 11/4 | Introduction to machine learning | [Slides](./slides/slides_ml_lm.pdf)  | -
M 11/8 | Linear modeling I | Same slides as R 11/3 <br> RMarkdown activity: `linear_modeling`  |-
W 11/10 | Linear modeling II | Same slides/activity  | Homework 9: Data reshaping with `tidyr` <br>  [Link to instructions](./homeworks/hw9/hw9_instructions.html)
R 11/11 | Linear modeling III  | Same slides/activity |
M 11/15 | Introduction to logistic regression | [Slides](./slides/slides_logistic.pdf) | -
W 11/17 | Logistic regression II |  RMarkdown activity: `logistic_regression` | Homework 10: Linear modeling  <br>  [Link to instructions](./homeworks/hw10/hw10_instructions.html)
R 11/18 | Logistic regression III | Same slides/activity | -
M 11/22 | Introduction to UNIX I | [Cheatsheet](./tutorials/unix_cheatsheet.html) | -
W 11/24 | **CLASS IS OVER ZOOM TODAY!!** <br> Introduction to Final Project | [Link to proposal and project instructions](./homeworks/project/project_proposal_instructions.html) <br> [Link to proposal Rmd template](./homeworks/project/proposal_template.Rmd)  | Homework 11: Logistic regression  <br>  [Link to instructions](./homeworks/hw11/hw11_instructions.html)
R 11/25 | _No class: Thanksgiving_  | - |
M 11/29 | Introduction to `git` and GitHub | [Cheatsheet](./tutorials/github_cheatsheet.html) <br> [Graphical Cheatsheet](./tutorials/github_infographics/github_intro.pdf) | -
W 12/1 | `git` and GitHub, continued | - | Homework 12: Final Project Proposal. _This homework may NOT be dropped._ <br> (The below links are the same as those shown on 11/24) <br> [Link to instructions](./homeworks/project/project_proposal_instructions.html) <br> [Link to Rmd template](./homeworks/project/proposal_template.Rmd)
R 12/2 | Final Project Setup | - | -
M 12/6 | Open Work: Final Project | - | -
W 12/8 | Optional Grabbag! <br> How to make your own website <br> Setting up R/RStudio on your computer <br> Statistical tests in R| - | -


**Final project due Tuesday December, 14th by 11:59 PM. [Link to instructions](./homeworks/project/project_proposal_instructions.html)**
