---
title: '"Data Science for Biologists" Resources'
author: "Stephanie J. Spielman, PhD"
date: "Spring 2021"
output: 
  html_document:
    highlight: tango
    theme: flatly
---

> Note: Bolded resources were written by Dr. Spielman.


## General resources

+ [`tidyverse` homepage, official documentation, and cheatsheets](https://www.tidyverse.org/)
  + Official documentation for using the tidyverse. Reference pages are "how-to" guides for using specific functions. **A go-to resource!**
    + [`ggplot2` command reference](https://ggplot2.tidyverse.org/reference/) 
    + [`readr` command reference](https://readr.tidyverse.org/reference/) 
    + [`dplyr` command reference](https://dplyr.tidyverse.org/reference/) 
    + [`tidyr` command reference](https://tidyr.tidyverse.org/reference/) 
    + [`stringr` command reference](https://stringr.tidyverse.org/reference/) 
    + [`forcats` command reference](https://forcats.tidyverse.org/reference/) 
  
+ Vignettes: Introductory tutorials for R packages
  + [`dplyr`: One-table verbs](https://cran.r-project.org/web/packages/dplyr/vignettes/dplyr.html)
  + [`dplyr`: Two-table verbs](https://cran.r-project.org/web/packages/dplyr/vignettes/two-table.html) 
    + Note: We may not get to this topic during Spring 2021 due to remote instruction limitations.
  + [Pivoting with `tidyr`](https://cran.r-project.org/web/packages/tidyr/vignettes/pivot.html)
  + [Introduction to `forcats`](https://cran.r-project.org/web/packages/forcats/vignettes/forcats.html)
  + [Introduction to `stringr`](https://cran.r-project.org/web/packages/stringr/vignettes/stringr.html)
  + [Regular expressions with `stringr`](https://cran.r-project.org/web/packages/stringr/vignettes/regular-expressions.html)
+ [RStudio Cloud primers](https://rstudio.cloud/learn/primers)
  + Interactive resources for practicing certain R and `tidyverse` skills
  + Recommended primers: "The Basics", "Work with Data", "Visualize data", "Tidy your data." The rest are beyond the scope of our class.
+ [R for Data Science](https://r4ds.had.co.nz/) by Garrett Grolemund and Hadley Wickham
  + The "official" book for working with the tidyverse. Examples in the book may assume more background knowledge than computing novices have.
+ [`ggplot2`: Elegant Graphics for Data Analysis](https://ggplot2-book.org/index.html) by Hadley Wickham, Danielle Navarro, and Thomas Lin Pederse
  + The `ggplot2` book.
+ [Data Visualization: A Practical Introduction](https://socviz.co/) by Kieran Healy
  + Introduces `ggplot2`, including the philosophy of the grammar of graphics and using many geoms. Again, some examples may assume more background knowledge than computing novices have.
  + Don't buy it! The whole book is there under "Menu."
  + Chapter 3 in particular introduces `ggplot2`
+ [Fundamentals of Data Visualization](https://clauswilke.com/dataviz) by Claus O. Wilke
  + Introduces concepts and principles in data visualization. This book does not contain code or teach `ggplot2`.
  + Chapter 5 in particular catalogs common types of data visualizations
+ [Twitter for Scientists](https://t4scientists.com/) and  [Twitter for R Programmers](https://www.t4rstats.com/)
  + Comprehensive and clear introductions to using twitter and interacting with the extreme;y wonderful `#rstats` community
+ [Tidyverse style guide](https://style.tidyverse.org/)
  + A resource of recommended code style when programming in the `tidyverse`. 
+ [RStudio Resources (all levels of videos/tutorials)](https://resources.rstudio.com/)
  + Expansive set of webinars compiled by RStudio. Many may be beyond the scope of our class.
+ [The "Tidy Data" paper by Hadley Wickham](https://vita.had.co.nz/papers/tidy-data.pdf)
  + Introduces the philosophy of "tidy data"
  
## Other classes with free online materials

+ [STAT545 Resources (**EXCELLENT** background)](https://stat545.com/)
  + E-book that accompanies a different class that teaches many of the same skills we are learning here, but assumes more statistics/programming background
  + Recommended book sections:
    + [`ggplot2` Tutorial](https://stat545.com/ggplot2-tutorial.html)
    + [Introduction to `dplyr`](https://stat545.com/dplyr-intro.html)
    + [Single-table `dplyr` functions](https://stat545.com/dplyr-single.html)
    + [When one tibble is not enough](https://stat545.com/multiple-tibbles.html) 
      + Note: We may not get to this topic during Spring 2021 due to remote instruction limitations.

+ [Introduction to Data Science e-book](https://rafalab.github.io/dsbook/)
  + Comprehensive data science book. Many topics in this book are more advanced than the scope of this class, but there are also many useful and relevant chapters.
  + Recommended book sections:
    + [R basics](https://rafalab.github.io/dsbook/r-basics.html), specifically sections 2.1-2.7
    + [`ggplot2`](https://rafalab.github.io/dsbook/ggplot2.html), specifically sections 7.1-7.10
    + [Visualizing data distributions](https://rafalab.github.io/dsbook/distributions.html), specifically sections 8.1, 8.5, 8.6, 8.12-8.17
    + [Data visualization in practice](https://rafalab.github.io/dsbook/gapminder.html), all sections
    + [Data visualization principles](https://rafalab.github.io/dsbook/data-visualization-principles.html), all sections
    + [The `tidyverse`](https://rafalab.github.io/dsbook/tidyverse.html), specifically sections 4.1-4.10 and 4.14
    + [Importing data](https://rafalab.github.io/dsbook/importing-data.html)
    + [Organizing with UNIX](https://rafalab.github.io/dsbook/unix.html), specifically sections 38.1 - 38.7
    + [Git and GitHub](https://rafalab.github.io/dsbook/git.html), all sections
    + [Reproducible projects with RStudio and R markdown](https://rafalab.github.io/dsbook/reproducible-projects-with-rstudio-and-r-markdown.html), all sections
    
+ [Data Science in a Box](https://datasciencebox.org/index.html)
  + A collection of resources, lessons, tutorials, and exercises for mastering data science techniques in R within the `tidyverse` framework. Of particular interest is the [Exploring Data](https://datasciencebox.org/exploring-data.html) section.
+ [Calling Bullshit Course Website](https://callingbullshit.org/) by Carl Bergstrom and Jevin West


## Interactive exercises from Dr. Spielman

*Note: These links are only likely to be live during the semester this course is being taught. They will not be available over the summer or winter break. If you would like access to these resources during off-season, please email Dr. Spielman and she will hook you up.*

+ [**Introduction to data types and their relationship to figures**](https://rowanbiosci.shinyapps.io/data_types_figures/)
+ [**Understanding the different types of plots**](https://rowanbiosci.shinyapps.io/types_of_plots/)
+ [**Introduction to R exercises**](https://rowanbiosci.shinyapps.io/intro_R/)
+ [**Introduction to `ggplot2` exercises**](https://rowanbiosci.shinyapps.io/intro_ggplot2/)
+ [**Introduction to `dplyr` exercises**](https://rowanbiosci.shinyapps.io/intro_dplyr/)


## Additional `ggplot2`-specific resources

+ [R for the Rest of Us: Overview of the grammar of graphics](https://rfortherestofus.com/2019/07/a-short-overview-of-the-grammar-of-graphics/)
  + Short video introducing the conceptual underpinnings of the grammar of graphics
+ [All the R colors you ever wanted to use!!](./tutorials/Rcolor.pdf)
+ [Official `ggplot2` command reference](https://ggplot2.tidyverse.org/reference/) 
+ [Chapter Three from "Data Visualization: A practical introduction"](https://socviz.co/makeplot.html) 
+ [**Reference: Customizing Colors and Fills**](./tutorials/color_fill_scales.html)
+ [**Reference: Customizing themes**](./tutorials/themes.html)
+ [**Reference: Customizing axes**](./tutorials/axes.html)

## Other static tutorials 

+ [**Introduction to R tutorial**](./tutorials/introduction_to_R.html)
+ [**Reference: Saving plots and reading/writing data**](./tutorials/readr_ggsave.html)
+ [**Reference: Greatest hits of `dplyr`**](./tutorials/dplyr_onetable.html) 
+ [**Linear modeling tutorial**](./tutorials/lm_tutorial.html) 
+ [**UNIX cheatsheet**](./tutorials/unix_cheatsheet.html)
+ [**Git(hub) cheatsheet**](./tutorials/github_cheatsheet.html)
+ [**Github infographic**](./tutorials/github_infographics/github_intro.pdf)
