---
title: 'Template: Homework #11'
author: "Data Science for Biologists, Fall 2021"
date: "Submit this completed Rmd file to Canvas on Wednesday 11/24/21 by 11:59 PM"
output: 
  html_document:
    theme: lumen
    highlight: tango
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, fig.width = 6, fig.height = 4)

# Always load libraries in the setup chunk:
library(tidyverse) # allows you to use ggplot2, readr, forcats, etc.
library(ds4b.materials) # contains the pima dataset
library(pROC) # allows ROC analysis
```



## Questions

<br><br>

#### Question 1

```{r q1}


```

<br>


#### Question 2

```{r q2}


```

Replace this with your 1 SPELL-CHECKED AND REASONABLY GRAMMAR-CHECKED sentence explaining which is preferred and why.

<br>



#### Question 3

```{r q3}


```

<br>

#### Question 4


```{r q4}


```

<br>

#### Question 5

```{r q5}


```


<br>

#### Question 6

```{r q6}


```

Replace this with your 1 SPELL-CHECKED AND REASONABLY GRAMMAR-CHECKED sentence explaining whether this woman likely has diabetes or not at the threshold.


