---
title: "UNIX Cheatsheet"
output: html_document
css: cheatsheet_style.css
---
<style type="text/css">
.main-container {
  max-width: 1800px;
  margin-left: auto;
  margin-right: auto;
}
</style>
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

> **This document is NOWHERE NEAR COMPREHENSIVE.** To learn more, visit Dr. Spielman's website and see "Resources"!




## Directory
  - A *folder* on your computer which contains files. UNIX filesystems are organized as hierarchical directories. 
  - Forward slashes divide levels in the nested hierarchy of directories, e.g. `/top_level_directory/second_level_directory`
  - The directory at the top of this hierarchy is called the **root** directory and is denoted simply as `/`. 

## Path
  - The *address* to a directory or file on your computer. There are, generally, two types of paths:
    - **Absolute/full path** represents the path of a given directory/file beginning at the root directory.
    - **Relative path** represents the path of a given directory/file relative to the working/current directory.
- Your **home directory** is the top-level of *your account* (`<>` signifies PLACEHOLDER text):
	- **Mac:** `/Users/<yourusername>/` (for me, `/Users/spielman/`)
	- **PC**: `C:\Users\<yourusername>\` <-- NOT UNIX!!
	- **Rstudio Cloud Project**: `/cloud/project/`
	- **Linux**: `/home/<yourusername/`


## Basic UNIX commands

Command | Description &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; | Examples
-------|--------------|----------- 
`cd` | **C**hange **d**irectory |  `cd Desktop` <br> `cd .. # one directory back` <br> `cd   # shortcut to go home` <br> `cd ~ # shortcut to go home`
`ls` | **L**i**s**t files and directories in current directory. |  `ls` <br> `ls -l # display long` <br> `ls -a # show hidden files` <br> `ls *Rmd # list all files that end with "Rmd"`
`pwd` | Display the path of the current directory (aka **p**rint **w**orking **d**irectory) | `pwd # yup that's it!`
`rm` | **R**e**m**ove a file or directory (use `rm -r`). **Warning: This is PERMANENT!.** | `rm file_I_dont_need.txt` <br> `rm -r directory_I_dont_need/`
`cp` | **C**o**p**y a file or directory(use `cp -r`) | `cp oldfile.txt newfile.txt` <br> `cp oldfile.txt .. # make a copy of the file to live one directory up` <br> `cp -r first_directory second_directory`
`mv` | **M**o**v**e or rename a file or directory (_original file is changed_ - like "cut" aka ctl+X) |  `cp oldfile.txt newfile.txt` <br> `cp oldfile.txt .. # MOVE the file to live one directory up`
`mkdir` | Create a new directory (aka **m**a**k**e **dir**ectory) | `mkdir new_directory`
`touch` | Create an empty file. | `touch new_blank_file.txt`
`cat` | Display contents of a file (aka con**cat**enate. this command can do more than this FYI) |  `cat file_whose_contents_i_want_to_see.txt`
`head` and `tail` | Display the first or last 10 lines of a file. | `head file_whose_contents_i_want_to_see.txt` 
`man` | Display documentation about a command (aka **man**ual). These are not well-written. You have been warned. *To exit just press* `q` | `man ls # look up how to use ls` 
`clear` | **Clear** screen (simply scroll up for past commands). Can also use Ctrl + L | `clear # yup that's it!`
`history`| View history of recent past commands | `history # yup that's it!`

## Shortcuts and symbols

Shortcut/symbol | Description
----------|-----
`Ctrl + C` | Kills current process/command
`*` | wildcard character
`tab` (tab key) | autocomplete word
`↑` (up arrow)| scroll back through previous commands
`.` | Current directory
`..` | One directory level up 
`~` | Home directory

